# Generated by Django 4.2.7 on 2023-11-22 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='favoutite_color',
            new_name='favourite_color',
        ),
    ]
